#!/usr/bin/env bash
# Regenerates BOARD.md from the frontmatter of epics/*.md and stories/*.md
set -euo pipefail
cd "$(dirname "$0")"
fm() { sed -n "s/^$2: *//p" "$1" | head -1 | sed -E 's/^"(.*)"$/\1/'; }
{
  echo "# Board index"
  echo
  echo "_Generated by \`gen_board.sh\` — do not edit by hand. Status lives in each card's frontmatter._"
  echo
  echo "## Epics"
  echo
  echo "| ID | Title | Priority | Lane | Status |"
  echo "|---|---|---|---|---|"
  for f in epics/*.md; do
    echo "| [$(fm "$f" id)]($f) | $(fm "$f" title) | $(fm "$f" priority) | $(fm "$f" lane) | $(fm "$f" status) |"
  done
  echo
  echo "## Stories"
  echo
  echo "| ID | Title | Epic | Prio | Size | Lane | Depends on | Status |"
  echo "|---|---|---|---|---|---|---|---|"
  for f in stories/*.md; do
    deps=$(fm "$f" depends_on | tr -d '[]')
    echo "| [$(fm "$f" id)]($f) | $(fm "$f" title) | $(fm "$f" epic) | $(fm "$f" priority) | $(fm "$f" size) | $(fm "$f" lane) | ${deps:--} | $(fm "$f" status) |"
  done
  echo
  echo "## Counts"
  echo
  for s in backlog ready in-progress review done; do
    n=$(grep -l "^status: $s$" stories/*.md 2>/dev/null | wc -l | tr -d ' ' || true)
    echo "- $s: $n"
  done
} > BOARD.md
echo "BOARD.md regenerated"
