// Pure helpers behind tools/list_content_assets.dart, kept separate so they
// can be unit tested (tools/test/list_content_assets_test.dart).

import 'dart:io';

/// The app package that owns the content bundle (US-007: assets stay where
/// Flutter needs them), relative to the repository root.
const String contentAppDir = 'apps/psy_trainer';

/// Root of the content bundle, relative to [contentAppDir] (and to that
/// package's `pubspec.yaml`, where the asset list is registered).
const String contentAssetRoot = 'assets/content';

/// Folder under [contentAssetRoot] that is never shipped.
const String contentExamplesFolder = 'examples';

const String contentAssetsBeginMarker =
    '  # BEGIN content assets (generated by tools/list_content_assets.dart)';
const String contentAssetsEndMarker = '  # END content assets';

/// Every directory under `apps/psy_trainer/assets/content/` (itself
/// included, `examples/` excluded), as paths relative to [contentAppDir]
/// (i.e. the form `apps/psy_trainer/pubspec.yaml` expects) with a trailing
/// slash, sorted.
///
/// Empty directories are listed too: `flutter build` accepts them and it
/// keeps the list stable while a family folder is being filled.
List<String> listContentAssetDirectories(String repoRoot) {
  final appRoot = '$repoRoot/$contentAppDir';
  final root = Directory('$appRoot/$contentAssetRoot');
  if (!root.existsSync()) return const [];
  final dirs = <String>['$contentAssetRoot/'];
  for (final entity in root.listSync(recursive: true)) {
    if (entity is! Directory) continue;
    final relative = entity.path
        .substring(appRoot.length + 1)
        .replaceAll('\\', '/');
    final segments = relative.split('/');
    if (segments.length > 2 && segments[2] == contentExamplesFolder) continue;
    dirs.add('$relative/');
  }
  return dirs..sort();
}

/// The `- assets/content/...` entries currently listed in [pubspec] (the
/// app's `pubspec.yaml`, not the workspace root's).
Set<String> registeredContentAssets(String pubspec) {
  final entries = <String>{};
  for (final line in pubspec.split('\n')) {
    final match = RegExp(r'^\s*-\s*(assets/content/\S*)\s*$').firstMatch(line);
    if (match != null) entries.add(match.group(1)!);
  }
  return entries;
}

/// The YAML lines of the `assets:` section for [dirs].
String formatContentAssets(List<String> dirs) {
  final buffer = StringBuffer('  assets:\n');
  for (final dir in dirs) {
    buffer.writeln('    - $dir');
  }
  return buffer.toString();
}

/// [pubspec] with the block between the markers replaced by the list for
/// [dirs]. Throws a [StateError] when the markers are missing.
String replaceContentAssets(String pubspec, List<String> dirs) {
  final begin = pubspec.indexOf(contentAssetsBeginMarker);
  final end = pubspec.indexOf(contentAssetsEndMarker);
  if (begin < 0 || end < 0 || end < begin) {
    throw StateError(
      'pubspec.yaml has no "$contentAssetsBeginMarker" / '
      '"$contentAssetsEndMarker" markers',
    );
  }
  final head = pubspec.substring(0, begin + contentAssetsBeginMarker.length);
  final tail = pubspec.substring(end);
  return '$head\n${formatContentAssets(dirs)}$tail';
}
