import 'package:drift/drift.dart';

import '../../repositories/model/session.dart';
import '../converters.dart';
import 'base_tables.dart';

// User data. Every row has a uuid v4 id generated by the repository layer
// (never by SQLite) so rows can be merged with a remote store later.

/// One practice or exam session. [mode] and [status] are stored by enum
/// name (`practice`, `inProgress`...).
@DataClassName('SessionRow')
@TableIndex(name: 'sessions_started_at', columns: {#startedAt})
@TableIndex(
  name: 'sessions_family_started_at',
  columns: {#familyId, #startedAt},
)
class Sessions extends Table with AuditedTable {
  TextColumn get mode => textEnum<SessionMode>()();

  /// Set for practice sessions (one family); null for exams.
  TextColumn get familyId => text().nullable()();

  /// Set for exam sessions; null for practice.
  TextColumn get blueprintId => text().nullable()();
  DateTimeColumn get startedAt => dateTime()();
  DateTimeColumn get endedAt => dateTime().nullable()();
  TextColumn get status => textEnum<SessionStatus>()();

  /// Final score in the engine's own unit (e.g. 0..1 or points); null until
  /// the session is finished.
  RealColumn get score => real().nullable()();

  /// Engine/launcher configuration (difficulty, item count, timer, realism
  /// options...). Free-form so engines can evolve without a migration.
  TextColumn get config => text().map(const JsonMapConverter())();
}

/// One answered (or timed-out) stimulus. Cadence-driven activities (n-back,
/// rules S-R) produce many rows per second; ordering within a session is by
/// [position], never by timestamp.
@DataClassName('AttemptRow')
@TableIndex(name: 'attempts_session_position', columns: {#sessionId, #position})
@TableIndex(
  name: 'attempts_family_answered_at',
  columns: {#familyId, #answeredAt},
)
@TableIndex(name: 'attempts_item', columns: {#itemId})
class Attempts extends Table with AuditedTable {
  TextColumn get sessionId => text().references(Sessions, #id)();

  /// Denormalised from the item/section so per-family aggregates never need
  /// the `items` table (generated items are not in it).
  TextColumn get familyId => text()();

  /// Content id for bank items; null for generated items (see [origin]).
  TextColumn get itemId => text().nullable()();

  /// `{generatorId, seed, params}` for generated items; null for bank items.
  TextColumn get origin => text().map(const JsonMapConverter()).nullable()();

  /// Engine-specific answer payload; null when no answer was given.
  TextColumn get answer => text().map(const JsonMapConverter()).nullable()();
  BoolColumn get isCorrect => boolean()();
  IntColumn get responseMs => integer()();

  /// 0-based rank of the stimulus within the session.
  IntColumn get position => integer()();

  /// Exam sessions only: index of the blueprint section.
  IntColumn get sectionIndex => integer().nullable()();
  DateTimeColumn get answeredAt => dateTime()();
}

/// Per bank item counters, maintained by an upsert on every attempt. Feeds
/// "retry my mistakes" (US-054) and adaptive difficulty (US-053).
@DataClassName('ItemStatRow')
@TableIndex(name: 'item_stats_item', columns: {#itemId}, unique: true)
@TableIndex(
  name: 'item_stats_family_last_correct',
  columns: {#familyId, #lastCorrect},
)
class ItemStats extends Table with AuditedTable {
  TextColumn get itemId => text()();
  TextColumn get familyId => text()();
  IntColumn get seen => integer()();
  IntColumn get correct => integer()();
  IntColumn get totalResponseMs => integer()();
  BoolColumn get lastCorrect => boolean()();
  DateTimeColumn get lastSeenAt => dateTime()();
}

/// Leitner state of one flashcard (US-042).
@DataClassName('FlashcardReviewRow')
@TableIndex(
  name: 'flashcard_reviews_card',
  columns: {#flashcardId},
  unique: true,
)
@TableIndex(name: 'flashcard_reviews_due', columns: {#deckId, #nextReviewAt})
class FlashcardReviews extends Table with AuditedTable {
  TextColumn get flashcardId => text()();
  TextColumn get deckId => text()();
  IntColumn get box => integer()();
  IntColumn get reviews => integer()();
  IntColumn get lapses => integer()();
  DateTimeColumn get lastReviewedAt => dateTime().nullable()();
  DateTimeColumn get nextReviewAt => dateTime()();
}

/// Lessons the user has read (US-044).
@DataClassName('LessonProgressRow')
@TableIndex(name: 'lesson_progress_lesson', columns: {#lessonId}, unique: true)
class LessonProgress extends Table with AuditedTable {
  TextColumn get lessonId => text()();
  DateTimeColumn get readAt => dateTime()();
}

/// Single-row profile (`id == UserProfiles.singletonId`).
@DataClassName('UserProfileRow')
class UserProfiles extends Table with AuditedTable {
  static const String singletonId = 'me';

  @override
  String get tableName => 'user_profile';

  DateTimeColumn get examDate => dateTime().nullable()();

  /// `psy0` | `psy1` | `psy2`; null until onboarding.
  TextColumn get targetStage => text().nullable()();
  TextColumn get locale => text()();
  TextColumn get settings => text().map(const JsonMapConverter())();
}
